# Generated by Django 5.0.6 on 2024-07-11 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devbotapp', '0003_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='UIRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_palette', models.JSONField(blank=True, null=True)),
                ('font', models.CharField(blank=True, max_length=255, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Devbotapp.project')),
            ],
        ),
    ]
