# Generated by Django 5.0.6 on 2024-07-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devbotapp', '0005_uirequirement_color_choice_uirequirement_font_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uirequirement',
            name='color_palette',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
