# Generated by Django 5.0.6 on 2024-07-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devbotapp', '0006_alter_uirequirement_color_palette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uirequirement',
            name='color_choice',
            field=models.CharField(choices=[('Generated', 'Generated'), ('Customized', 'Customized')], default='Generated', max_length=20),
        ),
        migrations.AlterField(
            model_name='uirequirement',
            name='font',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='uirequirement',
            name='font_color',
            field=models.CharField(max_length=7),
        ),
    ]
