# Generated by Django 5.0.6 on 2024-07-11 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devbotapp', '0007_alter_uirequirement_color_choice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('development_framework', models.CharField(choices=[('Ruby on Rails', 'Ruby on Rails'), ('Django', 'Django'), ('Laravel', 'Laravel'), ('Spring Boot', 'Spring Boot'), ('ASP.NET Core', 'ASP.NET Core'), ('Express.js', 'Express.js'), ('Angular', 'Angular'), ('React', 'React'), ('Vue.js', 'Vue.js'), ('Flask', 'Flask'), ('Meteor', 'Meteor'), ('Svelte', 'Svelte'), ('Next.js', 'Next.js'), ('Nuxt.js', 'Nuxt.js'), ('Phoenix', 'Phoenix'), ('CodeIgniter', 'CodeIgniter'), ('CakePHP', 'CakePHP'), ('Symfony', 'Symfony'), ('Play Framework', 'Play Framework'), ('Koa.js', 'Koa.js')], max_length=50)),
                ('cms', models.CharField(choices=[('WordPress', 'WordPress'), ('Joomla', 'Joomla'), ('Drupal', 'Drupal'), ('Magento', 'Magento'), ('Shopify', 'Shopify'), ('Squarespace', 'Squarespace'), ('Wix', 'Wix'), ('Weebly', 'Weebly'), ('TYPO3', 'TYPO3'), ('Ghost', 'Ghost'), ('Umbraco', 'Umbraco'), ('Sitecore', 'Sitecore'), ('Craft CMS', 'Craft CMS'), ('Concrete5', 'Concrete5'), ('Contentful', 'Contentful'), ('Strapi', 'Strapi'), ('October CMS', 'October CMS'), ('SilverStripe', 'SilverStripe'), ('HubSpot CMS', 'HubSpot CMS'), ('Webflow', 'Webflow'), ('Customized', 'Customized')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_requirements', to='Devbotapp.project')),
            ],
        ),
    ]
