# Generated by Django 5.0.6 on 2024-07-11 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devbotapp', '0008_technicalrequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Devbotapp.project'),
        ),
    ]
