# Generated by Django 5.0.6 on 2024-07-11 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devbotapp', '0009_userresponse_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='project',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='project_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Devbotapp.projecttype'),
        ),
    ]
