# Generated by Django 5.0.6 on 2024-07-12 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devbotapp', '0010_remove_userresponse_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='project_type',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Devbotapp.project'),
        ),
    ]
