# Generated by Django 5.0.6 on 2024-07-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devbotapp', '0011_remove_userresponse_project_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalrequirement',
            name='development_framework',
            field=models.CharField(choices=[('Static HTML', 'Static HTML'), ('Django', 'Django'), ('Laravel', 'Laravel'), ('ASP.NET Core', 'ASP.NET Core'), ('Angular', 'Angular'), ('React', 'React'), ('Vue.js', 'Vue.js'), ('Flask', 'Flask'), ('Meteor', 'Meteor'), ('Svelte', 'Svelte'), ('Next.js', 'Next.js'), ('Nuxt.js', 'Nuxt.js'), ('Phoenix', 'Phoenix'), ('CodeIgniter', 'CodeIgniter'), ('CakePHP', 'CakePHP'), ('Symfony', 'Symfony'), ('Play Framework', 'Play Framework'), ('Koa.js', 'Koa.js')], max_length=50),
        ),
    ]
