# Generated by Django 5.0.6 on 2024-07-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devbotapp', '0013_bot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='llm_choice',
        ),
        migrations.AddField(
            model_name='bot',
            name='llm',
            field=models.CharField(choices=[('llama3', 'Llama3'), ('gpt-4', 'GPT-4'), ('gpt-4o', 'GPT-4o')], default='llama3', max_length=50),
        ),
    ]
